output_path: output
output_name: output_file

#input_img_path: ../../geo_data/test.tif
input_img_path: ../../geo_data/flair_toy_sample_IMG_065120.tif
#input_img_path: ../../geo_data/N-33-60-D-c-4-2.tif
channels: [1, 2, 3, 4, 5]

img_pixels_detection: 512
margin: 128
output_type: "class_prob"  # options: [class_prob, argmax]
n_classes: 19


model_weights: ../weights/FLAIR-INC_rgbie_15cl_resnet34-unet_weights.pth
model_framework: 
    model_provider: SegmentationModelsPytorch
    HuggingFace:
        org_model: 
    SegmentationModelsPytorch:
        encoder_decoder: resnet34_unet


batch_size: 4
use_gpu: true
model_name: 'unet'
encoder_name: 'resnet34'
num_worker: 0

write_dataframe: False

norma_task: 
  - norm_type: custom 
    norm_means: [105.08, 110.87, 101.82, 106.38, 53.26]
    norm_stds: [52.17, 45.38, 44, 39.69, 79.3]
